### ISSUE TITLE
Different result for the same picture

### ISSUE THREAD

**Issue by hyclover** [charlesCXK/Depth2HHA-python#10]
I extracted depth images from the mat file of NUYDv2 official dataset. Here is my extraction code:
`f=h5py.File( "nyu_depth_v2_labeled.mat")
depths=f["depths"]
depths=np.array(depths)
depths = depths / max * 255
depths = depths.transpose((0,2,1))`

As the official described, the depth values are in meters. When I extracted depth images, I didn't change units. I just normalized.
> depths – HxWxN matrix of in-painted depth maps where H and W are the height and width, respectively and N is the number of images. The values of the depth elements are in meters.

Then I used your code to get HHA images. I remove the number 10000 because as I understand it, my depth images are already in meters.
`D = cv2.imread(os.path.join(root, '000001.png'), cv2.COLOR_BGR2GRAY)`
Unfortunately, I got a weird HHA image which was different from your result in demo.
Can you tell me what my problem is?
![image](https://user-images.githubusercontent.com/44492334/99638933-f422c800-2a81-11eb-9b35-8813706b3c77.png)
                                  my HHA image
![image](https://user-images.githubusercontent.com/44492334/99639094-26342a00-2a82-11eb-8cb5-0e058f5ed800.png)
                                 my depth image

**Comment by hyclover** [comment]
I tried to use `RD = cv2.imread(os.path.join(root, '000001.png'), cv2.COLOR_BGR2GRAY) / 255 * max` and just got the normal result. So the question is did I not  use the right depth value before?
![image](https://user-images.githubusercontent.com/44492334/99645044-aa3de000-2a89-11eb-8a1a-b79f9e172aca.png)
   my final result

**Comment by charlesCXK** [comment]
@hyclover 
Hi, I think the depth map should not be normalized or be viewed as a 3-channel color map. If you normalize the depth map, such as `depths = depths / max * 255`, the maximum depth value would be 255 meters, and the hyper-parameters used in our code will be not suitable.

**Comment by hyclover** [comment]
> @hyclover
> Hi, I think the depth map should not be normalized or be viewed as a 3-channel color map. If you normalize the depth map, such as `depths = depths / max * 255`, the maximum depth value would be 255 meters, and the hyper-parameters used in our code will be not suitable.

I just got the code from the Internet to extract the depth image. Would you mind sharing your code for extracting depth images from official Matlab file `nyu_depth_v2_labeled.mat`. Thanks very much!

**Comment by charlesCXK** [comment]
@hyclover 
As you illustrated above, I think you just need to remove the normalization code. Finally, the depth value of NYU Depth v2 images will lie in [0, 20] meters for most cases, since it is an in-door dataset.
