### ISSUE TITLE
Unit conversion

### ISSUE THREAD

**Issue by WW-0** [charlesCXK/Depth2HHA-python#12]
“The depth image array passed to function getHHA should in 'meter'. So in my demo code, I divide it with 10000 to modify the unit.”    meter，10000 or 1000？

**Comment by charlesCXK** [comment]
Please check the code: https://github.com/charlesCXK/Depth2HHA-python/blob/00b2f43f8909152d272275487ad0630b045eb66b/getHHA.py#L14

**Comment by WW-0** [comment]
> Please check the code:
> 
> https://github.com/charlesCXK/Depth2HHA-python/blob/00b2f43f8909152d272275487ad0630b045eb66b/getHHA.py#L14
所以不是很明白为什么是除以10000，这步骤是干嘛的，如果是单位换算米和毫米之间不应该是1000吗

**Comment by charlesCXK** [comment]
你好，原始图片没有说是用mm单位保存的，所以按他保存的单位处以10000后是“米”

**Comment by WW-0** [comment]
你好，谢谢回复。
1. 为什么要除以10000呢，有什么作用呢，我是把原始图片的深度值打出来查看的值大概是2000+，所以我猜测是单位是毫米，并且我看kinect的值都是毫米。
2. 我看matlab版本saveHHA.m  中有这么一句‘’‘ D = double(D)/1000; %The unit of the element inside D is 'meter' ’‘’
所以我有点疑惑，方便加下联系方式进行进一步沟通吗

**Comment by charlesCXK** [comment]
你可以用我提供的demo读进来试试，我刚看了处以10000之后单位是米没问题的。最大、最小的深度值都是个位数。你说的情况我不确定是读错了还是数据跟我不一样，总之保证输入函数的单位是米即可。

**Comment by WW-0** [comment]
谢谢回复。刚才仔细检查了下，matlab版代码里的深度图和pyton版demo里的图数值差了10倍，所以才导致不一样。只要最终保证单位是米即可
