### ISSUE TITLE
Suggestions for a 10x faster implementation.

### ISSUE THREAD

**Issue by hongfz16** [charlesCXK/Depth2HHA-python#14]
Hi. Thank you for sharing the code. After going through your code, I found two places where the implementation could be faster.

1. In the function `filterItChopOff`, you could replace `signal.convolve2d` with `cv2.filter2D` which is a faster implementation.
2. In the function `rotatePC`, it is better to convert `R`, which is originally the type of `dtype('O')`, to `dtype(np.float64)`, which is going to boost the performance of `np.dot`.

After the above two modifications, the execution time of `getHHA.py` is **~2.5s** compared to the original **~23s**.

**Comment by charlesCXK** [comment]
@hongfz16 
Thanks for your helpful advice! I will test the solution you provide and update this repo if it has no problem.

**Comment by charlesCXK** [comment]
I follow your suggestions and find the bottleneck of the running speed lies in the `R`. It was the type of `object`, which is slow for `np.dot` function. I have updated the optimized code. Thanks again!
