### ISSUE TITLE
Should missingMask == 0 instead of 1?

### ISSUE THREAD

**Issue by jiunyen-ching** [charlesCXK/Depth2HHA-python#7]
Hi, under `computeNormalsSquareSupport` function, I was wondering if we should compare msisingMask to 0 instead of 1? Because the values at the borders and missing depths are 0.

A sample image of the NYU0003_0000.png (rawDepth)
![NYU0003_0000_rawDepths](https://user-images.githubusercontent.com/25114361/85943622-ca96c200-b963-11ea-94a4-87fb4816d13d.png)

**Comment by charlesCXK** [comment]
Let's see how missingMask is defined:
`missingMask = (RD == 0);` (in getHHA.py)
So `missingMask==1` means this area is missing and its depth value is 0.

**Comment by jiunyen-ching** [comment]
Ahh I see! Thanks for pointing it out!
