### ISSUE TITLE
getHHA file angle question

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [charlesCXK/Depth2HHA-python#8]
In your getHHA.py file, you have the line

I[:, :, 0] = (angle + 128 - 90)

where did the numbers 128 - 90 (=28) come from?

**Comment by charlesCXK** [comment]
@JamesMcCullochDickens 
Hi, this is copied from the official implementation. https://github.com/s-gupta/rcnn-depth/blob/ad56ddd57b0fe35b177d6dfe29b5e0601accbf18/rcnn/saveHHA.m#L18
