### ISSUE TITLE
Convert LiDAR sparse depth?

### ISSUE THREAD

**Issue by mzy97** [charlesCXK/Depth2HHA-python#9]
Thank you for sharing the tool.

Could LiDAR sparse depth (only 5-10% points on the image plane are valid) be converted to HHA depth map?
And if it could convert, will HHA map better for sparse depth feature extraction?

**Comment by charlesCXK** [comment]
@mzy97 
Hi, I think it is hard to generate HHA maps using LiDAR sparse depth. For example, when calculating HHA, we need to estimate the direction of the gravity and sparse depth makes this inaccurate.
